In [21]:
import pandas as pd
from IPython.display import display
df=pd.read_csv(r"C:\Users\Rohini jadhav\Downloads\intense_stock_data.csv")
df["Volatility"]=df["High"]-df["Low"]
volatility=df["Volatility"]
print(f"volatility : {volatility}")

# to find the stock with high volatility days(volatility>100)
def classify_volatility(v):
    if v > 100:
        return "High volatility"
    else: 
        return"Low volatility"
        
df["Volatility Performance"]=df["Volatility"].apply(classify_volatility)
counts= df["Volatility Performance"].value_counts()
print (f"\nDay type count: {counts}")

high_volatility_stock=df[df["Volatility Performance"]=="High volatility"]
grouped_data=high_volatility_stock.groupby("Stock").size()

all_stock_volatility= grouped_data.idxmax()
most_high_volatile_stock=grouped_data.max()

top_five=df.sort_values(by="Volatility",ascending=False).head(5)

print(f"\ntop five stokcs with   high volatility days: \n{top_five[['Date','Stock','Volatility']]}")
print(f"\n stocks with high volatility days:\n{grouped_data}")
print(f"\nstock with most volatility days :\n{most_high_volatile_stock} : {all_stock_volatility}")

# creating extra rows of code cus i am yet begginer  using same term by modifying it 
# and applying it,thats still hard, i get confused , so i am taking long route , but 
#i will be there eventually  with practice .

def volatility_type(Volatility):
    if Volatility> 100:
        return"gain"
    elif Volatility<100:
        return"loss"
    else: 
        return"no change"
df["Volatility"]=df["High"]-df["Low"]       
df["volatility type"]=df["Volatility"].apply(volatility_type)
avg_volatility=df.groupby("volatility type")["Volatility"].mean().round(2)
print(f"\naverage volatility compare :\n{avg_volatility}")
display(df)

volatility : 0       80.30
1       93.58
2       48.43
3      123.83
4       93.81
        ...
495     87.05
496    161.72
497     38.26
498    136.34
499     85.10
Name: Volatility, Length: 500, dtype: float64

Day type count: Volatility Performance
Low volatility     346
High volatility    154
Name: count, dtype: int64

top five stokcs with   high volatility days:
           Date     Stock  Volatility
12   2023-01-13       TCS      196.82
471  2023-03-13  RELIANCE      190.39
248  2023-02-18     WIPRO      190.31
437  2023-02-07  RELIANCE      174.72
217  2023-01-18     WIPRO      169.57

 stocks with high volatility days:
Stock
HDFC        29
INFY        29
RELIANCE    28
TCS         36
WIPRO       32
dtype: int64

stock with most volatility days :
36 : TCS

average volatility compare :
volatility type
gain    124.71
loss     67.71
Name: Volatility, dtype: float64

,Date,Stock,Open,Close,High,Low,Volume,Volatility,Volatility Performance,volatility type
0,2023-01-01,TCS,1561.81,1606.90,1616.16,1535.86,5998,80.30,Low volatility,loss
1,2023-01-02,TCS,2426.07,2468.59,2495.69,2402.11,1162,93.58,Low volatility,loss
2,2023-01-03,TCS,2097.99,2101.49,2145.14,2096.71,2974,48.43,Low volatility,loss
3,2023-01-04,TCS,1897.99,1968.15,2004.76,1880.93,4291,123.83,High volatility,gain
4,2023-01-05,TCS,1234.03,1268.50,1308.83,1215.02,9461,93.81,Low volatility,loss
...,...,...,...,...,...,...,...,...,...,...
495,2023-04-06,RELIANCE,1530.03,1509.24,1563.44,1476.39,6004,87.05,Low volatility,loss
496,2023-04-07,RELIANCE,1875.48,1958.40,1989.37,1827.65,7652,161.72,High volatility,gain
497,2023-04-08,RELIANCE,1116.60,1104.96,1139.77,1101.51,7416,38.26,Low volatility,loss
498,2023-04-09,RELIANCE,2461.59,2576.09,2595.08,2458.74,4170,136.34,High volatility,gain
499,2023-04-10,RELIANCE,2479.32,2507.14,2550.31,2465.21,4835,85.10,Low volatility,loss